site_name: DEEPS Documentation
site_url: https://SamMachariaPhD.github.io/exam-system-docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
  features:
    - navigation.sections

nav:
  - Home: index.md

plugins:
  - search