# DEEPS Documentation Site Configuration

# Site settings
title: "DEEPS Documentation"
description: "Departmental Exam Processing System - Comprehensive academic data management for educational institutions"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samuelokello.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - getting-started.md
  - user-guide/first-run.md
  - user-guide/student-management.md
  - user-guide/assessments.md
  - user-guide/reports.md
  - technical/system-requirements.md

# Collections
collections:
  user_guide:
    output: true
    permalink: /:collection/:name/
  technical:
    output: true
    permalink: /:collection/:name/
  legal:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "user_guide"
    values:
      layout: "page"
      category: "User Guide"
  - scope:
      path: ""
      type: "technical"
    values:
      layout: "page"
      category: "Technical Documentation"
  - scope:
      path: ""
      type: "legal"
    values:
      layout: "page"
      category: "Legal Information"

# SEO settings
author: "Dedan Kimathi University of Technology"
twitter:
  username: dkut_official
social:
  name: DEDAN KIMATHI UNIVERSITY OF TECHNOLOGY
  links:
    - https://www.dkut.ac.ke

# Google Analytics (optional - institution can add their tracking ID)
# google_analytics: UA-XXXXXXXX-X

# Repository settings
repository: "samuelokello/exam-system-docs"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/